export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_VALIDATION = 'LOGIN_VALIDATION';
export const TOGGLE_PASSWORD = 'TOGGLE_PASSWORD';

//OPPORTUNITIES Actions
export const LOAD_OPPORTUNITIES_START = 'LOAD_OPPORTUNITIES_START';
export const LOAD_OPPORTUNITIES_SUCCESS = 'LOAD_OPPORTUNITIES_SUCCESS';
export const LOAD_OPPORTUNITIES_FAIL = 'LOAD_OPPORTUNITIES_FAIL';
export const FETCH_OPPORTUNITIES = 'FETCH_OPPORTUNITIES';
export const OPPORTUNITIES_SELECTED = 'OPPORTUNITIES_SELECTED';
export const CREAT_OPPORTTIES = 'CREAT_OPPORTTIES';

//common
export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';

//accounts
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const CREATE_ACCOUNTS = 'CREATE_ACCOUNTS';
export const DELET_ACCOUNTS = 'DELET_ACCOUNTS';
