export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//OPPORTUNITIES Actions
export const LOAD_OPPORTUNITIES_START = 'LOAD_OPPORTUNITIES_START';
export const LOAD_OPPORTUNITIES_SUCCESS = 'LOAD_OPPORTUNITIES_SUCCESS';
export const LOAD_OPPORTUNITIES_FAIL = 'LOAD_OPPORTUNITIES_FAIL';
export const FETCH_OPPORTUNITIES = 'FETCH_OPPORTUNITIES';
export const OPPORTUNITIES_SELECTED = 'OPPORTUNITIES_SELECTED';

//common
export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
